<?php

//Custom fields
if(function_exists("register_field_group"))
{

	acf_add_local_field_group(array(
		'key' => 'group_5c744b5e93e4e',
		'title' => 'WhitePaper Blocks: Loop',
		'fields' => array(
			array(
				'key' => 'field_5c744b7df70a1',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c744babf70a2',
				'label' => 'Block ID',
				'name' => 'block_id',
				'type' => 'text',
				'instructions' => 'A unique CSS ID for this block. Make sure to use all lower case and dashes instead of spaces',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c744ca5f70a4',
				'label' => 'Post Type',
				'name' => 'post_type',
				'type' => 'select',
				'instructions' => 'What kind of posts do you want to show? You can choose blog posts, pages, or a custom post type.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'post' => 'post',
					'page' => 'page',
					'attachment' => 'attachment',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5c744c1ff70a3',
				'label' => 'Number of Posts to Display',
				'name' => 'num_posts',
				'type' => 'number',
				'instructions' => 'The maximum number of posts to be displayed from your selected post type',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => 1,
			),
			array(
				'key' => 'field_5c744f5af70a5',
				'label' => 'Post Classes',
				'name' => 'post_class',
				'type' => 'text',
				'instructions' => 'One or more CSS classes to be added to each post in this block. Separate classes with a space, but make sure that each class uses all lower case and dashes instead of spaces.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c744ff7f70a6',
				'label' => 'Before Loop',
				'name' => 'before_loop_layout',
				'type' => 'textarea',
				'instructions' => 'Information to be placed before the loop. This will only be shown once, no matter how many posts are displayed. You can use HTML and Boostrap for formatting. You can also use handlebar codes to display dynamic information. This section is totally optional.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c74514ef70a7',
				'label' => 'Post Layout',
				'name' => 'post_layout',
				'type' => 'textarea',
				'instructions' => 'How would you like the individual posts in the loop to be laid out? You can use HTML and Boostrap for formatting. You can also use handlebar codes to display dynamic information. If you aren\'t sure, you can leave this blank and just use the default.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c745248f70a8',
				'label' => 'After Loop',
				'name' => 'after_loop_layout',
				'type' => 'textarea',
				'instructions' => 'Information to be placed after the loop. This will only be shown once, no matter how many posts are displayed. You can use HTML and Boostrap for formatting. You can also use handlebar codes to display dynamic information. This section is totally optional.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
			'key' => 'field_5c96ba66d5584',
			'label' => 'Advanced Query Options',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			),
			array(
				'key' => 'field_5c96d161ade01',
				'label' => 'Taxonomy Slug',
				'name' => 'taxonomy',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'category',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c96d411ade02',
				'label' => 'Taxonomy Term',
				'name' => 'taxonomy_term',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'my-category',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/loop',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

  register_field_group(array (
		'id' => 'acf_templates',
		'title' => 'Templates',
		'fields' => array (
			array (
				'key' => 'field_5975529261dbc',
				'label' => 'Header',
				'name' => 'header',
				'type' => 'select',
				'choices' => array (
					'default' => 'Default',
          'a1-b1' => 'A1-B1',
          'a1-b12' => 'A1-B12',
          'a1-b123' => 'A1-B123',
          'a12-b1' => 'A12-B1',
          'a12-b12' => 'A12-B12',
          'b1' => 'B1',
          'b12' => 'B12',
          'b123' => 'B123',
					'm-a1-b1' => 'M-A1-B1',
					'm-a1-b12' => 'M-A1-B12',
					'm-a1-b123' => 'M-A1-B123',
					'm-a12-b1' => 'M-A12-B1',
					'm-a12-b12' => 'M-A12-B12',
					'm-b1' => 'M-B1',
					'm-b12' => 'M-B12',
					'm-b123' => 'M-B123',
				),
				'default_value' => 'default',
				'allow_null' => 0,
				'multiple' => 0,
      ),
        array (
  				'key' => 'field_597812602b921',
  				'label' => 'Footer',
  				'name' => 'footer',
  				'type' => 'select',
  				'choices' => array (
  					'default' => 'Default',
					'a1-b1' => 'A1-B1',
					'a1-b2' => 'A1-B2',
					'a1-b12' => 'A1-B12',
					'a1-b13' => 'A1-B13',
					'a1-b23' => 'A1-B23',
					'a1-b123' => 'A1-B123',
					'b12' => 'B12'
  				),
  				'default_value' => 'default',
  				'allow_null' => 0,
  				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_ctas',
		'title' => 'CTA\'s',
		'fields' => array (
			array (
				'key' => 'field_58f2f06cb45e7',
				'label' => 'Link',
				'name' => 'link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
      array (
				'key' => 'field_59753a49a55db',
				'label' => 'Font Awesome Icon Class',
				'name' => 'font_awesome_icon_class',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'fa-icon-name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'ctas',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio',
		'title' => 'Portfolio',
		'fields' => array (
			array (
				'key' => 'field_58f2efb43e07f',
				'label' => 'CMS',
				'name' => 'cms',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
  register_field_group(array (
		'id' => 'acf_locations',
		'title' => 'Locations',
		'fields' => array (
			array (
				'key' => 'field_5a95ae4f2cfbd',
				'label' => 'Address Line 1',
				'name' => 'address_line_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a95ae8e2cfbe',
				'label' => 'Address Line 2',
				'name' => 'address_line_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a95aeaf2cfbf',
				'label' => 'City',
				'name' => 'city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a95aeb72cfc0',
				'label' => 'State',
				'name' => 'state',
				'type' => 'select',
				'choices' => array (
					'Alabama' => 'Alabama',
					'Alaska' => 'Alaska',
					'Arizona' => 'Arizona',
					'Arkansas' => 'Arkansas',
					'California' => 'California',
					'Colorado' => 'Colorado',
					'Connecticut' => 'Connecticut',
					'Delaware' => 'Delaware',
					'Florida' => 'Florida',
					'Georgia' => 'Georgia',
					'Hawaii' => 'Hawaii',
					'Idaho' => 'Idaho',
					'Illinois' => 'Illinois',
					'Indiana' => 'Indiana',
					'Iowa' => 'Iowa',
					'Kansas' => 'Kansas',
					'Kentucky' => 'Kentucky',
					'Louisiana' => 'Louisiana',
					'Maine' => 'Maine',
					'Maryland' => 'Maryland',
					'Massachusetts' => 'Massachusetts',
					'Michigan' => 'Michigan',
					'Minnesota' => 'Minnesota',
					'Mississippi' => 'Mississippi',
					'Missouri' => 'Missouri',
					'Montana' => 'Montana',
					'Nebraska' => 'Nebraska',
					'Nevada' => 'Nevada',
					'New Hampshire' => 'New Hampshire',
					'New Jersey' => 'New Jersey',
					'New Mexico' => 'New Mexico',
					'New York' => 'New York',
					'North Carolina' => 'North Carolina',
					'North Dakota' => 'North Dakota',
					'Ohio' => 'Ohio',
					'Oklahoma' => 'Oklahoma',
					'Oregon' => 'Oregon',
					'Pennsylvania' => 'Pennsylvania',
					'Rhode Island' => 'Rhode Island',
					'South Carolina' => 'South Carolina',
					'South Dakota' => 'South Dakota',
					'Tennessee' => 'Tennessee',
					'Texas' => 'Texas',
					'Utah' => 'Utah',
					'Vermont' => 'Vermont',
					'Virginia' => 'Virginia',
					'Washington' => 'Washington',
					'Washington DC' => 'Washington DC',
					'West Virginia' => 'West Virginia',
					'Wisconsin' => 'Wisconsin',
					'Wyoming' => 'Wyoming',
				),
				'default_value' => 'Alabama',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a95af542cfc1',
				'label' => 'ZIP Code',
				'name' => 'zip_code',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
        'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a95af6a2cfc2',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
        'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a95af9b2cfc3',
				'label' => 'Fax Number',
				'name' => 'fax_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5a95afe42cfc4',
				'label' => 'Email Address',
				'name' => 'email_address',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'locations',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
  register_field_group(array (
		'id' => 'acf_staff',
		'title' => 'Staff',
		'fields' => array (
      array(
  			'key' => 'field_5c9cbd405861b',
  			'label' => 'Position',
  			'name' => 'staff_position',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  		),
			array (
				'key' => 'field_5a99cbc902e95',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a99cc0a02e96',
				'label' => 'Email Address',
				'name' => 'email_address',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'staff',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
  acf_add_local_field_group(array(
  	'key' => 'group_5c87fc5b17270',
  	'title' => 'Testimonials',
  	'fields' => array(
  		array(
  			'key' => 'field_5c87fc66deda4',
  			'label' => 'Reviewer Name',
  			'name' => 'reviewer_name',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => 'John Doe',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  		),
  		array(
  			'key' => 'field_5c87fcb5deda5',
  			'label' => 'Star Rating',
  			'name' => 'star_rating',
  			'type' => 'number',
  			'instructions' => '',
  			'required' => 1,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => 'Stars',
  			'min' => 1,
  			'max' => 5,
  			'step' => 1,
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'testimonials',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'default',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 1,
  	'description' => '',
  ));
}